### ISSUE TITLE
Getting "TypeError: Object is not a function Modal node_modules/react-simple-modal-provider/dist/Modal.js:25" when trying to implement the example code

### ISSUE THREAD

**Issue by Ujjwal-N** [seungdeng17/react-simple-modal-provider#17]
I am an absolute beginner so I am probably missing something really simple.

App.js
```
import logo from './logo.svg';
import './App.css';
import { ModalProvider } from 'react-simple-modal-provider';
import Feed from './components/feed';
import BasicModal from './components/BasicModal';
import ConsumePage from './components/ConsumePage';

function App() {
  return (
    <ModalProvider value={[BasicModal]}>
      <Feed />
      <ConsumePage />
    </ModalProvider>
  );
}

export default App;
```

BasicModal.jsx
```
import Modal, { useModalState } from "react-simple-modal-provider";

export default ({ children }) => {
    const { isOpen, setOpen } = useModalState();

    return (
        <Modal
            id={"BasicModal"}
            consumer={children}
            isOpen={isOpen}
            setOpen={setOpen}
        >
            <span>😆</span>
        </Modal>
    );
};
```

ConsumePage.jsx
```
import { useModal } from "react-simple-modal-provider";

export default () => {
    const { open: openModal } = useModal("BasicModal");

    return <button onClick={openModal}>Open</button>;
};
```

Thank you in advance. Sorry if this post is not detailed enough, let me know what else to include.

**Comment by seungdeng17** [comment]
@Ujjwal-N 
from v1.7.1, return value of useModalState was changed to an array.
check the line using the useModalState of your BasicModal component.

```javascript
const [isOpen, setOpen] = useModalState();
```

**Comment by Ujjwal-N** [comment]
Thank you for your quick response. Even after changing that line of code, I still get the same error.

![Screen Shot 12](https://user-images.githubusercontent.com/15056315/129830487-212e013c-b375-45d2-b031-3329e483d7df.jpg)

Here is the repo I am working on (frontend branch): https://github.com/hearnjohn/immutable-news/tree/frontend

**Comment by seungdeng17** [comment]
@Ujjwal-N 
check your project index.js.
if your in strict mode, turn it off and try it.

```javascript
ReactDOM.render(<App />, document.getElementById('root'));
```

**Comment by Ujjwal-N** [comment]
Strict mode was the issue. Thank you so much for your help and for providing this fantastic resource :)
