### ISSUE TITLE
SSR ReferenceError: document is not defined

### ISSUE THREAD

**Issue by mdwt** [seungdeng17/react-simple-modal-provider#19]
The following error occurs when using the portal in NextJS:  ReferenceError: document is not defined

Looks like the Portal.ts defines head and body constants - is there a way to move that to the useEffect() so that SSR will not be affected?

**Comment by seungdeng17** [comment]
@mdwt
modified, now supports nextjs
you can update it (v1.9.0)
thanks for the report
